/**
 * HTML output formatter
 *
 * Zero-dependency implementation
 *
 * @packageDocumentation
 */

import type { DependencyTree, AnalysisResult } from '../../types.js';
import { escapeHtml } from '../../utils/string.js';

/**
 * CSS styles for HTML output
 */
const STYLES = `
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    line-height: 1.6;
    color: #333;
    background: #f5f5f5;
    padding: 20px;
  }
  .container {
    max-width: 1200px;
    margin: 0 auto;
    background: white;
    border-radius: 8px;
    box-shadow: 0 2px 10px rgba(0,0,0,0.1);
    overflow: hidden;
  }
  .header {
    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
    color: white;
    padding: 30px;
  }
  .header h1 { font-size: 28px; margin-bottom: 10px; }
  .header .subtitle { opacity: 0.9; }
  .content { padding: 30px; }
  .section { margin-bottom: 30px; }
  .section h2 {
    font-size: 20px;
    margin-bottom: 15px;
    padding-bottom: 10px;
    border-bottom: 2px solid #667eea;
  }
  .summary {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
    gap: 15px;
    margin-bottom: 20px;
  }
  .summary-card {
    background: #f8f9fa;
    padding: 15px;
    border-radius: 6px;
    border-left: 4px solid #667eea;
  }
  .summary-card .label {
    font-size: 12px;
    color: #666;
    text-transform: uppercase;
  }
  .summary-card .value {
    font-size: 24px;
    font-weight: bold;
    color: #333;
  }
  .tree {
    font-family: 'Courier New', monospace;
    font-size: 13px;
    background: #f8f9fa;
    padding: 15px;
    border-radius: 6px;
    overflow-x: auto;
    white-space: pre;
  }
  table {
    width: 100%;
    border-collapse: collapse;
    margin-bottom: 15px;
  }
  th, td {
    padding: 12px;
    text-align: left;
    border-bottom: 1px solid #e0e0e0;
  }
  th {
    background: #f8f9fa;
    font-weight: 600;
    color: #555;
  }
  tr:hover { background: #f8f9fa; }
  .badge {
    display: inline-block;
    padding: 4px 8px;
    border-radius: 4px;
    font-size: 12px;
    font-weight: 600;
  }
  .badge.critical { background: #dc3545; color: white; }
  .badge.high { background: #fd7e14; color: white; }
  .badge.moderate { background: #ffc107; color: #333; }
  .badge.low { background: #28a745; color: white; }
  .badge.major { background: #dc3545; color: white; }
  .badge.minor { background: #ffc107; color: #333; }
  .badge.patch { background: #28a745; color: white; }
  .list { list-style: none; }
  .list li {
    padding: 8px 0;
    border-bottom: 1px solid #e0e0e0;
  }
  .list li:last-child { border-bottom: none; }
  .chain {
    background: #f8f9fa;
    padding: 10px;
    border-radius: 4px;
    font-family: monospace;
    margin-bottom: 8px;
  }
  .footer {
    text-align: center;
    padding: 20px;
    color: #666;
    font-size: 14px;
    border-top: 1px solid #e0e0e0;
  }
  .footer a { color: #667eea; text-decoration: none; }
  .footer a:hover { text-decoration: underline; }
</style>
`;

/**
 * Convert dependency node to HTML tree
 * @param node - Dependency node
 * @param depth - Current depth
 */
function nodeToHtml(node: DependencyNode, depth: number = 0): string {
  const indent = '&nbsp;&nbsp;&nbsp;&nbsp;'.repeat(depth);
  const escapedName = escapeHtml(node.name);
  const escapedVersion = escapeHtml(node.version);

  let output = `${indent}${escapedName}@${escapedVersion}\n`;

  for (const child of node.dependencies) {
    output += nodeToHtml(child, depth + 1);
  }

  return output;
}

/**
 * Convert dependency tree to HTML
 * @param tree - Dependency tree
 */
export function treeToHtml(tree: DependencyTree): string {
  let output = '<div class="section">';
  output += '<h2>Dependency Tree</h2>';
  output += `<div class="tree">${escapeHtml(nodeToHtml(tree.root))}</div>`;
  output += `<p><strong>Total:</strong> ${tree.count} dependencies, <strong>Max depth:</strong> ${tree.depth}</p>`;
  output += '</div>';

  return output;
}

/**
 * Convert analysis result to HTML
 * @param result - Analysis result
 */
export function toHTML(result: AnalysisResult): string {
  let output = '<!DOCTYPE html>\n<html lang="en">\n<head>\n';
  output += '<meta charset="UTF-8">\n';
  output += '<meta name="viewport" content="width=device-width, initial-scale=1.0">\n';
  output += '<title>Dependency Analysis Report</title>\n';
  output += STYLES;
  output += '</head>\n<body>\n';
  output += '<div class="container">\n';

  // Header
  output += '<div class="header">\n';
  output += '<h1>Dependency Analysis Report</h1>\n';
  output += '<p class="subtitle">Generated by @oxog/deps</p>\n';
  output += '</div>\n';

  output += '<div class="content">\n';

  // Summary
  output += '<div class="summary">\n';
  output += '<div class="summary-card">\n';
  output += '<div class="label">Total Dependencies</div>\n';
  output += `<div class="value">${result.tree.count}</div>\n`;
  output += '</div>\n';

  output += '<div class="summary-card">\n';
  output += '<div class="label">Max Depth</div>\n';
  output += `<div class="value">${result.tree.depth}</div>\n`;
  output += '</div>\n';

  if (result.circular.length > 0) {
    output += '<div class="summary-card">\n';
    output += '<div class="label">Circular Dependencies</div>\n';
    output += `<div class="value">${result.circular.length}</div>\n`;
    output += '</div>\n';
  }

  if (result.size) {
    output += '<div class="summary-card">\n';
    output += '<div class="label">Total Size</div>\n';
    output += `<div class="value">${escapeHtml(result.size.totalFormatted)}</div>\n`;
    output += '</div>\n';
  }

  if (result.security && result.security.total > 0) {
    output += '<div class="summary-card">\n';
    output += '<div class="label">Vulnerabilities</div>\n';
    output += `<div class="value">${result.security.total}</div>\n`;
    output += '</div>\n';
  }

  output += '</div>\n';

  // Dependency Tree
  output += treeToHtml(result.tree);

  // Circular Dependencies
  if (result.circular.length > 0) {
    output += '<div class="section">\n';
    output += '<h2>Circular Dependencies</h2>\n';
    output += '<ul class="list">\n';

    for (const chain of result.circular) {
      output += '<li>\n';
      output += `<div class="chain">${escapeHtml(chain.join(' → '))} → ${escapeHtml(chain[0])}</div>\n`;
      output += '</li>\n';
    }

    output += '</ul>\n';
    output += '</div>\n';
  }

  // Unused Dependencies
  if (result.unused && result.unused.length > 0) {
    output += '<div class="section">\n';
    output += '<h2>Unused Dependencies</h2>\n';
    output += '<ul class="list">\n';

    for (const dep of result.unused) {
      output += `<li>${escapeHtml(dep)}</li>\n`;
    }

    output += '</ul>\n';
    output += '</div>\n';
  }

  // Missing Dependencies
  if (result.missing && result.missing.length > 0) {
    output += '<div class="section">\n';
    output += '<h2>Missing Dependencies</h2>\n';
    output += '<ul class="list">\n';

    for (const dep of result.missing) {
      output += `<li>${escapeHtml(dep)}</li>\n`;
    }

    output += '</ul>\n';
    output += '</div>\n';
  }

  // Duplicate Versions
  if (result.duplicates && Object.keys(result.duplicates).length > 0) {
    output += '<div class="section">\n';
    output += '<h2>Duplicate Versions</h2>\n';
    output += '<table>\n';
    output += '<thead><tr><th>Package</th><th>Versions</th></tr></thead>\n';
    output += '<tbody>\n';

    for (const [pkg, versions] of Object.entries(result.duplicates)) {
      output += '<tr>\n';
      output += `<td>${escapeHtml(pkg)}</td>\n`;
      output += `<td>${escapeHtml(versions.join(', '))}</td>\n`;
      output += '</tr>\n';
    }

    output += '</tbody>\n</table>\n';
    output += '</div>\n';
  }

  // Size Analysis
  if (result.size) {
    output += '<div class="section">\n';
    output += '<h2>Size Analysis</h2>\n';
    output += '<table>\n';
    output += '<thead><tr><th>Package</th><th>Size</th><th>Percentage</th></tr></thead>\n';
    output += '<tbody>\n';

    for (const pkg of result.size.packages) {
      output += '<tr>\n';
      output += `<td>${escapeHtml(pkg.name)}</td>\n`;
      output += `<td>${escapeHtml(pkg.sizeFormatted)}</td>\n`;
      output += `<td>${pkg.percentage}%</td>\n`;
      output += '</tr>\n';
    }

    output += '</tbody>\n</table>\n';
    output += '</div>\n';
  }

  // Update Suggestions
  if (result.updates && result.updates.length > 0) {
    output += '<div class="section">\n';
    output += '<h2>Available Updates</h2>\n';
    output += '<table>\n';
    output += '<thead><tr><th>Package</th><th>Current</th><th>Latest</th><th>Type</th></tr></thead>\n';
    output += '<tbody>\n';

    for (const update of result.updates) {
      output += '<tr>\n';
      output += `<td>${escapeHtml(update.name)}</td>\n`;
      output += `<td>${escapeHtml(update.current)}</td>\n`;
      output += `<td>${escapeHtml(update.latest)}</td>\n`;
      output += `<td><span class="badge ${update.type}">${update.type}</span></td>\n`;
      output += '</tr>\n';
    }

    output += '</tbody>\n</table>\n';
    output += '</div>\n';
  }

  // Security Audit
  if (result.security && result.security.total > 0) {
    output += '<div class="section">\n';
    output += '<h2>Security Vulnerabilities</h2>\n';
    output += `<p><strong>Total:</strong> ${result.security.total}</p>\n`;
    output += '<p>\n';
    output += `<span class="badge critical">Critical: ${result.security.bySeverity.critical}</span> `;
    output += `<span class="badge high">High: ${result.security.bySeverity.high}</span> `;
    output += `<span class="badge moderate">Moderate: ${result.security.bySeverity.moderate}</span> `;
    output += `<span class="badge low">Low: ${result.security.bySeverity.low}</span>\n`;
    output += '</p>\n';

    if (result.security.vulnerabilities.length > 0) {
      output += '<table>\n';
      output += '<thead><tr><th>Package</th><th>Severity</th><th>Title</th></tr></thead>\n';
      output += '<tbody>\n';

      for (const vuln of result.security.vulnerabilities) {
        output += '<tr>\n';
        output += `<td>${escapeHtml(vuln.package)}</td>\n`;
        output += `<td><span class="badge ${vuln.severity}">${vuln.severity}</span></td>\n`;
        output += `<td>${escapeHtml(vuln.title)}</td>\n`;
        output += '</tr>\n';
      }

      output += '</tbody>\n</table>\n';
    }

    output += '</div>\n';
  }

  output += '</div>\n';

  // Footer
  output += '<div class="footer">\n';
  output += '<p>&copy; 2025 Ersin Koç | MIT License</p>\n';
  output += '<p><a href="https://github.com/ersinkoc/deps">GitHub</a> | <a href="https://deps.oxog.dev">Documentation</a></p>\n';
  output += '</div>\n';

  output += '</div>\n';
  output += '</body>\n</html>';

  return output;
}
